# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  watch:
#    types: started
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      sendPost:
        description: ''
        required: false
        default: 'false'

jobs:
  build:

    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set hosts
      run: |
        sudo echo '36.158.229.112 cdn.u1.huluxia.com' | sudo tee -a /etc/hosts
    - name: Run
      env:
        key: ${{ secrets.key }}
        login: ${{ secrets.login }}
        id: ${{ secrets.id }}
        sender: ${{ secrets.sender }}
        to: ${{ secrets.to }}
        pass: ${{ secrets.pass }}
        sendpost: ${{ github.event.inputs.sendpost }}
        on: ${{ github.event_name }}
      run: |
        python -u jiezi.py
